apiVersion: kubevirt.io/v1                                                      
kind: KubeVirt                                                                  
metadata:                                                                       
  name: kubevirt                                                                
  namespace: kubevirt                                                           
spec:                                                                           
  configuration:                                                                
    seccompConfiguration:
      virtualMachineInstanceProfile:
        customProfile:
          localhostProfile: kubevirt/kubevirt.json
    migrations:                                                                 
      allowPostCopy: true                                                       
